### ISSUE TITLE
`docker-compose build` doesn't work

### ISSUE THREAD

**Issue by av-ast** [MrRTi/yc-remote-dev#1]
When I run `docker-compose build` it fails with the following message

```
(root) Additional property yc-terraform is not allowed
```

Here is a working version:
```
services:
  yc-terraform:
    build: .
    env_file:
      - .env
      - secrets.env
    stdin_open: true
    tty: true
    volumes:
      - .:/yc-terraform
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
```
